//
// Created by ozan on 03.03.21.
//

#ifndef INC_20_20_20_HELPER_TWENTYTWENTYTWENTYNOTIFICATIONMANGER_H
#define INC_20_20_20_HELPER_TWENTYTWENTYTWENTYNOTIFICATIONMANGER_H


class TwentyTwentyTwentyNotificationManger {

};


#endif //INC_20_20_20_HELPER_TWENTYTWENTYTWENTYNOTIFICATIONMANGER_H
